version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product-service-container
    restart: unless-stopped

  cart-service:
    build: ./cart-service
    container_name: cart-service-container
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service-container
    ports:
      - "3003:3003"
    environment:
      - CART_SERVICE_URL=http://cart-service:3002
    depends_on:
      - cart-service
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-container
    ports:
      - "3000:3000"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:3001
      - CART_SERVICE_URL=http://cart-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
    depends_on:
      - product-service
      - cart-service
      - order-service
    restart: unless-stopped